FROM docker.io/andimajore/biocyper_base:python3.10

#Sets default for BIOCYPHER_CONFIG
ARG BIOCYPHER_CONFIG=config/biocypher_docker_config.yaml
ENV USED_BIOCYPHER_CONFIG=$BIOCYPHER_CONFIG

WORKDIR /usr/app/
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install
COPY . ./
RUN cp ${USED_BIOCYPHER_CONFIG} config/biocypher_config.yaml
RUN python3 create_knowledge_graph.py