FROM docker.io/neo4j:4.4-enterprise
COPY ./data/neo4j /var/lib/neo4j/import/neo4j
COPY ./docker/* ./
RUN cat biocypher_entrypoint_patch.sh | cat - /startup/docker-entrypoint.sh > docker-entrypoint.sh && mv docker-entrypoint.sh /startup/ && chmod +x /startup/docker-entrypoint.sh